<?php
$page_title = 'SSL/TLS Manager';
ob_start();
?>

<div class="db-container">
    <div class="db-page-header">
        <h1>SSL/TLS Manager</h1>
        <p>Manage Let's Encrypt SSL certificates for your domains. SSL is normally provisioned automatically.</p>
    </div>

    <div class="db-section">
        <div class="table-responsive">
            <table class="db-table" id="sslTable">
                <thead>
                    <tr>
                        <th>Domain</th>
                        <th>SSL Status</th>
                        <th class="text-right">Actions</th>
                    </tr>
                </thead>
                <tbody id="sslList">
                    <tr>
                        <td colspan="3" class="text-center">Loading domains...</td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        <div class="alert alert-info mt-4" style="background:#e0f2fe; color:#0369a1; padding:15px; border-radius:5px; border:1px solid #bae6fd;">
            <div class="d-flex align-items-center gap-2">
                <i data-lucide="info" style="width:20px;height:20px;"></i>
                <span><strong>Note:</strong> SSL certificates are automatically generated by Traefik. If your domain is properly pointed to your server's IP address, it should automatically secure itself. You can force a retry by clicking "Install SSL" below.</span>
            </div>
        </div>
    </div>
</div>

<style>
    .db-container { padding: 10px; width: 100%; max-width: 100%; }
    .db-page-header h1 { font-size: 20px; font-weight: 500; margin: 0 0 5px 0; color: var(--text-primary); }
    .db-page-header p { color: var(--text-secondary); font-size: 13px; margin-bottom: 20px; }
    .db-section { background: var(--bg-card); border: 1px solid var(--border-color); border-radius: 4px; padding: 15px; margin-bottom: 20px; }
    
    .db-table { width: 100%; border-collapse: collapse; font-size: 13px; }
    .db-table th { background: var(--bg-input); padding: 12px 15px; text-align: left; font-weight: 500; color: var(--text-secondary); border-bottom: 1px solid var(--border-color); }
    .db-table td { padding: 12px 15px; border-bottom: 1px solid var(--border-color); vertical-align: middle; color: var(--text-primary); }
    .db-table tr:hover td { background: rgba(0, 0, 0, 0.02); }
    [data-theme="dark"] .db-table tr:hover td { background: rgba(255, 255, 255, 0.02); }
    
    .status-badge {
        display: inline-flex;
        align-items: center;
        gap: 6px;
        padding: 4px 10px;
        border-radius: 20px;
        font-size: 12px;
        font-weight: 500;
    }

    .status-badge.checking {
        background: rgba(139, 148, 158, 0.1);
        color: #8b949e;
    }

    .status-badge.active {
        background: rgba(60, 135, 58, 0.1);
        color: var(--primary);
    }

    .status-badge.uninstalled {
        background: rgba(218, 54, 51, 0.1);
        color: var(--danger, #da3633);
    }

    .status-badge i {
        width: 12px;
        height: 12px;
    }

    .btn:disabled {
        opacity: 0.6;
        cursor: not-allowed;
    }
</style>

<script>
    const SSL_API_URL = '<?= $base_url ?? '' ?>/api/v1';
    const TOKEN = document.querySelector('meta[name="api-token"]')?.content;
    let userDomains = [];

    async function loadDomains() {
        try {
            const response = await fetch(`${SSL_API_URL}/ssl`, {
                headers: { 'Authorization': `Bearer ${TOKEN}` }
            });
            if (!response.ok) throw new Error('Failed to fetch domains');
            
            userDomains = await response.json();
            renderTable();
            checkAllSSLStatuses();
            
        } catch (error) {
            console.error('Error loading domains:', error);
            document.getElementById('sslList').innerHTML = `
                <tr><td colspan="3" class="text-center text-danger">Error loading domains</td></tr>
            `;
        }
    }

    function renderTable() {
        const tbody = document.getElementById('sslList');
        
        if (userDomains.length === 0) {
            tbody.innerHTML = `<tr><td colspan="3" class="text-center">No domains found</td></tr>`;
            return;
        }

        tbody.innerHTML = userDomains.map(domain => `
            <tr>
                <td style="font-weight:500;">
                    <a href="http://${domain.domain_name}" target="_blank" style="color:var(--text-primary); text-decoration:none;">
                        ${domain.domain_name}
                    </a>
                </td>
                <td id="status-${domain.id}">
                    <span class="status-badge checking">
                        <i data-lucide="loader-2" class="spin-anim"></i> Checking...
                    </span>
                </td>
                <td class="text-right" id="action-${domain.id}">
                    <button class="btn btn-secondary btn-sm" disabled style="padding: 5px 12px; font-size:12px;">Checking...</button>
                </td>
            </tr>
        `).join('');

        lucide.createIcons();
    }

    async function checkAllSSLStatuses() {
        // Run checks sequentially or in parallel. Parallel is faster.
        const promises = userDomains.map(domain => checkSSLStatus(domain));
        await Promise.all(promises);
    }

    async function checkSSLStatus(domain) {
        try {
            const response = await fetch(`${SSL_API_URL}/ssl/check?domain=${domain.domain_name}`, {
                headers: { 'Authorization': `Bearer ${TOKEN}` }
            });
            
            if (!response.ok) throw new Error('Check failed');
            const data = await response.json();
            
            updateDomainRow(domain.id, domain.domain_name, data.status);
        } catch (error) {
            console.error(`Error checking SSL for ${domain.domain_name}:`, error);
            updateDomainRow(domain.id, domain.domain_name, 'error');
        }
    }

    function updateDomainRow(id, domainName, status) {
        const statusTd = document.getElementById(`status-${id}`);
        const actionTd = document.getElementById(`action-${id}`);
        
        if (!statusTd || !actionTd) return;

        if (status === 'active') {
            statusTd.innerHTML = `
                <span class="status-badge active">
                    <i data-lucide="shield-check"></i> Active
                </span>
            `;
            actionTd.innerHTML = `
                <button class="btn btn-secondary btn-sm" disabled style="padding: 5px 12px; font-size:12px; background:var(--bg-input); border-color:var(--border-color); color:var(--text-secondary);">
                    SSL Installed
                </button>
            `;
        } else {
            statusTd.innerHTML = `
                <span class="status-badge uninstalled">
                    <i data-lucide="shield-alert"></i> Uninstalled
                </span>
            `;
            actionTd.innerHTML = `
                <button class="btn btn-primary btn-sm" onclick="installSSL(${id}, '${domainName}')" style="padding: 5px 12px; font-size:12px;">
                    Install SSL
                </button>
            `;
        }
        lucide.createIcons();
    }

    async function installSSL(id, domainName) {
        const btn = document.querySelector(`#action-${id} button`);
        const originalText = btn.innerHTML;
        btn.innerHTML = `<i data-lucide="loader-2" class="spin-anim" style="width:14px;height:14px;vertical-align:middle;"></i> <span style="vertical-align:middle;">Installing...</span>`;
        btn.disabled = true;
        lucide.createIcons();

        try {
            const response = await fetch(`${SSL_API_URL}/ssl/install`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${TOKEN}`
                },
                body: JSON.stringify({ domain: domainName })
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || 'Failed to trigger installation');
            }

            showToast('SSL installation triggered! Please wait up to a minute for Traefik to issue the certificate.', 'success');
            
            // Re-check status after 5 seconds to see if it successfully generated
            setTimeout(() => {
                checkSSLStatus({ id: id, domain_name: domainName });
            }, 5000);
            
        } catch (error) {
            console.error('Install error:', error);
            showToast(error.message, 'error');
            btn.innerHTML = 'Install SSL';
            btn.disabled = false;
        }
    }

    document.addEventListener('DOMContentLoaded', loadDomains);
</script>

<?php
$content = ob_get_clean();
include __DIR__ . '/../../shared/layouts/main.php';
?>
